
language: c

env:
  - XCC=gcc HOST= PREFIX=/usr DEBUG="--enable-tests --enable-debug" WINE= LIBCURL=--without-libcurl JPEG=--without-jpeg PNG=--without-png
  - XCC=clang HOST= PREFIX=/usr DEBUG="--enable--tests --enable-debug" WINE= LIBCURL=--without-libcurl JPEG=--without-jpeg PNG=--without-png
  - XCC=i686-w64-mingw32-gcc HOST="--host=i686-w64-mingw32" PREFIX="/usr/i686-w64-mingw32" DEBUG="--enable--tests --enable-debug" WINE=wine
  - XCC=i586-mingw32msvc-gcc HOST="--host=i586-mingw32msvc" PREFIX="/usr/i586-mingw32msvc" WINE=wine
  - XCC=x86_64-w64-mingw32-gcc HOST="--host=x86_64-w64-mingw32" PREFIX="/usr/x86_64-w64-mingw32" DEBUG="--enable--tests --enable-debug" WINE=wine64
  - XCC=clang HOST= PREFIX=/usr DEBUG="--enable--tests --enable-debug" WINE= JPEG="--with-jpeg" PNG="--with-png"
  - XCC=clang HOST= PREFIX=/usr DEBUG="--enable--tests --enable-debug" WINE= GDKPIXBUF="--with-gdk-pixbuf2" JPEG=--without-jpeg PNG=--without-png
  - XCC=clang HOST= PREFIX=/usr DEBUG="--enable--tests --enable-debug" WINE= LIBCURL="--with-libcurl" JPEG=--without-jpeg PNG=--without-png
  - XCC=clang HOST= PREFIX=/usr DEBUG="--enable--tests --enable-debug" WINE= GD="--with-gd" JPEG=--without-jpeg PNG=--without-png
  - XCC=clang HOST= PREFIX=/usr DEBUG="--enable--tests --enable-debug" WINE= GDKPIXBUF="--with-gdk-pixbuf2" LIBCURL="--with-libcurl" JPEG=--without-jpeg PNG=--without-png
  - XCC=clang HOST= PREFIX=/usr DEBUG="--enable--tests --enable-debug" WINE= GD="--with-gd" LIBCURL="--with-libcurl" JPEG=--without-jpeg PNG=--without-png
  - XCC=clang HOST= PREFIX=/usr DEBUG="--enable--tests --enable-debug" WINE= GDKPIXBUF="--with-gdk-pixbuf2" GD="--with-gd" JPEG=--without-jpeg PNG=--without-png
  - XCC=clang HOST= PREFIX=/usr DEBUG="--enable--tests --enable-debug" WINE= GDKPIXBUF="--with-gdk-pixbuf2" GD="--with-gd" LIBCURL="--with-libcurl" JPEG=--without-jpeg PNG=--without-png
  - XCC=gcc HOST= PREFIX=/usr DEBUG="--enable--tests --enable-debug" WINE= GDKPIXBUF="--with-gdk-pixbuf2" GD="--with-gd" JPEG="--with-jpeg" PNG="--with-png" LIBCURL="--with-libcurl"
  - XCC=clang HOST= PREFIX=/usr DEBUG="--enable-tests --enable-debug" WINE= JPEG="--with-jpeg" PNG="--with-png" LIBCURL="--with-libcurl" GCOV="--enable-gcov" STATIC="--disable-shared"

before_install:
  - "sudo apt-get -qq update --force-yes > /dev/null"
  - "if [ x$GDKPIXBUF != x ]; then sudo apt-get -qq install pkg-config libgdk-pixbuf2.0-dev; fi"
  - "if [ x$GD != x ]; then sudo apt-get -qq install libgd2-xpm-dev; fi"
  - "if [ x$LIBCURL != x ]; then sudo apt-get -qq install libcurl4-openssl-dev; fi"
  - "if [ x$WINE = x ]; then sudo apt-get install -qq valgrind > /dev/null; fi"
  - "if [ x$WINE != x ]; then sudo apt-get install -qq wine > /dev/null; fi"
  - "if [ x$XCC = xclang ]; then sudo apt-get install -qq clang; fi"
  - "if [ x$XCC = xgcc ]; then sudo apt-get install -qq gcc; fi"
  - "if [ x$XCC = xi686-w64-mingw32-gcc ]; then sudo apt-get install -qq gcc-mingw-w64-i686 binutils-mingw-w64-i686; fi"
  - "if [ x$XCC = xi586-mingw32msvc-gcc ]; then sudo apt-get install -qq mingw32; fi"
  - "if [ x$XCC = xx86_64-w64-mingw32-gcc ]; then sudo apt-get install -qq gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64; fi"
  - "if [ x$GCOV != x ]; then sudo apt-get install libyaml-dev; fi"
  - "if [ x$GCOV != x ]; then sudo pip install cpp-coveralls pyyaml; fi"

before_script:
  - "CC=$XCC ./configure --prefix=${PREFIX} ${DEBUG} ${HOST} ${GDKPIXBUF} ${GD} ${LIBCURL} ${PNG} ${JPEG} ${GCOV} ${STATIC}"

script:
  - "make"
  - "sudo make install"
  - "make test | tee log | grep succeeded || (cat log|tail -n5; exit 1)"

after_success:
  - "make valgrind || (cat valgrind.log && exit 1)"
  - "make coveralls"
