
language: c

env:
  - XCC=clang HOST= WINE=
  - XCC=gcc HOST= WINE=
  - XCC=i686-w64-mingw32-gcc HOST="--host=i686-w64-mingw32" WINE=wine
  - XCC=i586-mingw32msvc-gcc HOST="--host=i586-mingw32msvc" WINE=wine
  - XCC=x86_64-w64-mingw32-gcc HOST="--host=x86_64-w64-mingw32" WINE=wine64
  - XCC=clang HOST= WINE= GDKPIXBUF="--with-gdk-pixbuf2"
  - XCC=clang HOST= WINE= LIBCURL="--with-libcurl"
  - XCC=clang HOST= WINE= GD="--with-gd"
  - XCC=clang HOST= WINE= GDKPIXBUF="--with-gdk-pixbuf2" LIBCURL="--with-libcurl"
  - XCC=clang HOST= WINE= GD="--with-gd" LIBCURL="--with-libcurl"
  - XCC=clang HOST= WINE= GDKPIXBUF="--with-gdk-pixbuf2" GD="--with-gd"
  - XCC=clang HOST= WINE= GDKPIXBUF="--with-gdk-pixbuf2" GD="--with-gd" LIBCURL="--with-libcurl"
  - XCC=clang HOST= WINE= GDKPIXBUF="--with-gdk-pixbuf2" GD="--with-gd" LIBCURL="--with-libcurl" GCOV="--enable-gcov" STATIC="--disable-shared"

before_install:
  - "sudo apt-get -qq update --force-yes > /dev/null"
  - "if [ x$GDKPIXBUF != x ]; then sudo apt-get -qq install pkg-config libgdk-pixbuf2.0-dev; fi"
  - "if [ x$GD != x ]; then sudo apt-get -qq install libgd2-xpm-dev; fi"
  - "if [ x$LIBCURL != x ]; then sudo apt-get -qq install libcurl4-openssl-dev; fi"
  - "if [ x$WINE = x ]; then sudo apt-get install -qq valgrind > /dev/null; fi"
  - "if [ x$WINE != x ]; then sudo apt-get install -qq wine > /dev/null; fi"
  - "if [ x$XCC = xclang ]; then sudo apt-get install -qq clang; fi"
  - "if [ x$XCC = xgcc ]; then sudo apt-get install -qq gcc; fi"
  - "if [ x$XCC = xi686-w64-mingw32-gcc ]; then sudo apt-get install -qq gcc-mingw-w64-i686 binutils-mingw-w64-i686; fi"
  - "if [ x$XCC = xi586-mingw32msvc-gcc ]; then sudo apt-get install -qq mingw32; fi"
  - "if [ x$XCC = xx86_64-w64-mingw32-gcc ]; then sudo apt-get install -qq gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64; fi"
  - "if [ x$GCOV != x ]; then sudo apt-get install libyaml-dev; fi"
  - "if [ x$GCOV != x ]; then sudo pip install cpp-coveralls pyyaml; fi"

before_script:
  - "echo ./configure --prefix=/usr ${HOST} ${GDKPIXBUF} ${GD} ${LIBCURL} ${GCOV} ${STATIC}"
  - "CC=$XCC ./configure --prefix=/usr ${HOST} ${GDKPIXBUF} ${GD} ${LIBCURL} ${GCOV} ${STATIC}"

script:
  - "make"
  - "sudo make install"
  - "$WINE converters/img2sixel images/snake.jpg > snake1.sixel"
  - "du -h snake1.sixel"
  - "$WINE converters/img2sixel -p16 images/snake.jpg > snake2.sixel"
  - "du -h snake2.sixel"
  - "$WINE converters/sixel2png -i snake1.sixel -o snake1.png"
  - "du -h snake1.png"
  - "$WINE converters/sixel2png < snake2.sixel > snake2.png"
  - "du -h snake2.png"
  - "$WINE converters/img2sixel snake1.png > snake3.sixel"
  - "du -h snake3.sixel"
  - "if [ x$GCOV != x ]; then make coveralls; fi"

after_success:
  - "if [ x$WINE = x ]; then make valgrind && exit 0 || cat valgrind.log && exit 1; fi"
